export const GET_SONG = "GET_SONG";
export const SONG_SUCCESS = "SONG_SUCCESS";
export const SONG_FAILED = "SONG_FAILED";
export const GET_SONG_DETAIL = "GET_SONG_DETAIL";
export const LOADING_TRUE = "LOADING_TRUE";
export const ERROR = "ERROR";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const ARTIST_SUCCESS = "ARTIST_SUCCESS";
export const ARTIST_FAILED = "ARTIST_FAILED";

export const ARTIST_POST_SUCCESS = "ARTIST_POST_SUCCESS";
export const ARTIST_POST_FAILED = "ARTIST_POST_FAILED";

export const GET_USERLOGIN = "GET_USERLOGIN";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const PAYMENT_UPDATE_SUCCES = "PAYMENT_UPDATE_SUCCES";
export const PAYMENT_UPDATE_FAIL = "PAYMENT_UPDATE_FAIL";

export const LOGOUT = "LOGOUT";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";
export const CLEAR_PROFILE = "CLEAR_PROFILE";

export const GET_TRANSACTION_SUCCESS = "GET_TRANSACTION_SUCCESS";
export const GET_TRANSACTION_ERROR = "GET_TRANSACTION_ERROR";

export const GET_HISTORY = "GET_HISTORY";
export const GET_HISTORY_EROR = "GET_HISTORY_EROR";

export const CLEAR_AUTH_ERROR = "CLEAR_AUTH_ERROR";

export const PAYMENT_ERROR = "PAYMENT_ERROR";
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
